server:
  port: 9527

spring:
  cloud:
    gateway:
      routes:
      - id: neo_route
        uri: http://localhost:8001
        filters:
        - AddRequestParameter=foo, bar
        predicates:
        - Method=GET


      discovery:
        locator:
          #是否与服务注册于发现组件进行结合，
          #通过 serviceId 转发到具体的服务实例。
          #默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: true

  application:
    name: cloud-gateway-eureka



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug